# CREATE A MENU DRIVEN PROGRAM THAT COLLECTS STUDENTS DETAIILS [NAME, EMAIL,PHONE] {USE DICTIONARY TO STORE STUDENT DETAILS}
# MENU OPTIONS <1. CREATE STUDENTS 2. SEARCH FOR STUDENTS 3. PRINT STUEDNTS >
